# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AvoidCoronaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AvoidCoronaApp
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Google-Maps-iOS-Utils'
  # for crawling
  pod 'Kanna'
end
